# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function
import os

def main():
    digits = dict()
    #            ABCDEFG.
    digits[0] = "11111100"
    digits[1] = "01100000"
    digits[2] = "11011010"
    digits[3] = "11110010"
    digits[4] = "01100110"
    digits[5] = "10110110"
    digits[6] = "10111110"
    digits[7] = "11100000"
    digits[8] = "11111110"
    digits[9] = "11110110"

    with open("7segment_decode.b", "w") as f:
        f.write("// file automatically generated by %s\n" %\
                os.path.basename(__file__))
        f.write("// DO NOT EDIT IT!\n")
        for v in range(256):
            d1 = v % 10
            d2 = (v // 10) % 10
            d3 = (v // 100) % 10

            f.write("%s%s%s\n" % (digits[d3], digits[d2], digits[d1]))

if __name__ == "__main__":
    main()
